name: Build and Test

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  

    - name: Build with Maven
      run: |
        ./gradlew build       

    - name: Run Tests
      run: |
        ./gradlew test  # Si vous utilisez Gradle
